<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Authors>Alex Vallière</Authors>
    <Version>0.5.28.0</Version>
    <PackageProjectUrl>https://github.com/AlexValliere/submarineEtaPlanner</PackageProjectUrl>
    <IconUrl>https://alexvalliere.github.io/submarineEtaPlanner/images/icon.png</IconUrl>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="SubmarineEtaPlanner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="CalculatedData.msgpack">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SubmarineEtaPlanner.Core\SubmarineEtaPlanner.Core.csproj" />
  </ItemGroup>
</Project>
